DATA:
  - data: data 1

ALGORITHMS:
  - model: NB
  - selector: HighestConfidence
  - stopper: Statistical

TRAINING:
  - batch proportion: 0.03
  - confidence: 0.9
  - verbose:

OUTPUT:
  - working path:
  - output path:
  - output metrics: true_recall model_recall relevants_seen

CLUSTERING:
  - clusterer: KM 3