DATA:
  - data: datasets

ALGORITHMS:
  - model: SVC
  - selector: HighestConfidence
  - stopper: ConsecutiveCount

TRAINING:
  - confidence: 0.95
  - verbose:

OUTPUT:
  - working path:
  - output path:
  - output metrics: true_recall model_recall