DATA:
  - data: datasets 1

ALGORITHMS:
  - model: SVC
  - selector: HighestConfidence
  - stopper: ConsecutiveCount 0.1

TRAINING:
  - batch proportion: 0.03
  - confidence: 0.95
  - verbose:

OUTPUT:
  - working path:
  - output path:
  - output metrics: true_recall model_recall